{
 "title": "tritron_v1",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "nv_inference_count",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 11, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "nv_inference_count{gpu_uuid=\"GPU-062e1754-3d86-87f9-4f8b-acf885b5a891\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "nv_gpu_utilization",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 11, "y": 0 },
   "targets": [
    {
     "expr": "nv_gpu_utilization{gpu_uuid=\"GPU-062e1754-3d86-87f9-4f8b-acf885b5a891\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "nv_gpu_memory_used",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 11, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "nv_gpu_memory_used_bytes{gpu_uuid=\"GPU-062e1754-3d86-87f9-4f8b-acf885b5a891\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "nv_inference_request_failure",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 11, "y": 11 },
   "targets": [
    {
     "expr": "nv_inference_request_failure{gpu_uuid=\"GPU-062e1754-3d86-87f9-4f8b-acf885b5a891\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}